## Data Analysis Process using Python of a Kaggle Dataset

### Using Kaggle API to install dataset

In [8]:
!pip install kaggle # Installing Kaggle library

Requirement already satisfied: kaggle in /Users/chandupeddi/opt/anaconda3/lib/python3.13/site-packages (2.0.0)
Requirement already satisfied: bleach in /Users/chandupeddi/opt/anaconda3/lib/python3.13/site-packages (from kaggle) (6.2.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.15 in /Users/chandupeddi/opt/anaconda3/lib/python3.13/site-packages (from kaggle) (0.1.15)
Requirement already satisfied: packaging in /Users/chandupeddi/opt/anaconda3/lib/python3.13/site-packages (from kaggle) (24.2)
Requirement already satisfied: protobuf in /Users/chandupeddi/opt/anaconda3/lib/python3.13/site-packages (from kaggle) (5.29.3)
Requirement already satisfied: python-dateutil in /Users/chandupeddi/opt/anaconda3/lib/python3.13/site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /Users/chandupeddi/opt/anaconda3/lib/python3.13/site-packages (from kaggle) (5.0.2)
Requirement already satisfied: requests in /Users/chandupeddi/opt/anaconda3/lib/python3.13/site-packages (from kaggle) (2.32.3)
Requirement already satisfied: tqdm in /Users/chandupeddi/opt/anaconda3/lib/python3.13/site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /Users/chandupeddi/opt/anaconda3/lib/python3.13/site-packages (from kaggle) (2.3.0)
Requirement already satisfied: webencodings in /Users/chandupeddi/opt/anaconda3/lib/python3.13/site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: six>=1.5 in /Users/chandupeddi/opt/anaconda3/lib/python3.13/site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /Users/chandupeddi/opt/anaconda3/lib/python3.13/site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/chandupeddi/opt/anaconda3/lib/python3.13/site-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/chandupeddi/opt/anaconda3/lib/python3.13/site-packages (from requests->kaggle) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in /Users/chandupeddi/opt/anaconda3/lib/python3.13/site-packages (from requests->kaggle) (2025.6.15)

### Saved my Kaggle API kaggle.json file in my local ~/.kaggle/kaggle.json location

Imported kaggle library and downloaded orders.csv.zip file from the kaggle

In [1]:
import kaggle
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading orders.csv.zip to /Users/chandupeddi/EndtoEnd
100%|████████████████████████████████████████| 200k/200k [00:00<00:00, 4.97MB/s]

As we know we cannot use the zip file we need to extract the zip file, so, I imported zipfile library and extracted the orders.csv.zip file to orders.csv file and placed in same location

In [2]:
import zipfile
zip_ref = zipfile.ZipFile('orders.csv.zip')
zip_ref.extractall() 
zip_ref.close()

After file got extracted, I imported pandas library and loaded the csv file

In [4]:
import pandas as pd 
df = pd.read_csv('orders.csv')

After got loaded I checked the content in the file using head function to see what columns and data is present in the file

In [7]:
df.head(20)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,Not Available,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3
10,11,2023-03-31,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,1470,1710,9,3
11,12,2023-12-25,Not Available,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,750,910,4,3
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,20,20,3,3
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,360,410,3,2
14,15,2023-11-09,unknown,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,60,70,5,5
15,16,2022-06-18,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,OFF-BI-10000756,0,0,3,5
16,17,2022-02-04,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,OFF-ST-10004186,610,670,6,3
17,18,2023-08-04,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,OFF-ST-10000107,60,60,2,4
18,19,2022-01-23,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,OFF-AR-10003056,10,10,2,4
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,170,210,3,3

In top 20 rows all the data looks good only the data in 'Ship Mode' column  have some missing data so first, I need to work on that missing data

In [10]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', 'Not Available', 'unknown',
       'First Class', nan, 'Same Day'], dtype=object)

For that I used unique function in that column and seen what values are there in the column

As I can see I need to deal with some null values rows, some rows who has the value as 'Not Available', and some rows having value 'unknown'.The rest of the values are good.

To make it simple I changing the 'Not Available' and 'unknown' values into null values so we can only need to deal with null values. For that while loading file I making a extra correction by saying consider this values as null values

In [12]:
df = pd.read_csv('orders.csv',na_values = ['Not Available','unknown'])

By passing this argument, I turned those values into null values

In [13]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

Second thing, I need to handle is column names, as I seen them some of column names have space between them and some have captial letters in middle so I changing every column name by changing every column to lowercase and replacing spaces with underscore

I am not using general method by writing every column and assigning it instead using functions

In [16]:
#General method 
#df.rename(columns = {'Order Id':'order_id','Country':'country'})
#Using functions
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [17]:
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

Now the data looks good and columns look nice

In the dataset we had cost of the item and MRP of the item and discount perecent gave for the item but it doesn't have at what price the item got sold after discount and how much discount gave and what is profit gain so we need to do some statstics to find those new values using given values and create three new columns as 'discount_price', 'sale_price',and profit.

In [22]:
df['discount_price']= df['list_price']*df['discount_percent']*0.01
df['sale_price'] = df['list_price'] - df['discount_price']
df['profit'] = df['sale_price'] - df['cost_price']

In [24]:
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount_price,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0

I got new three columns and respected values, so now I checking each column data type so I get an idea is there any types of changes needed or all are correctly formatted

In [27]:
df.dtypes

order_id              int64
order_date           object
ship_mode            object
segment              object
country              object
city                 object
state                object
postal_code           int64
region               object
category             object
sub_category         object
product_id           object
cost_price            int64
list_price            int64
quantity              int64
discount_percent      int64
discount_price      float64
sale_price          float64
profit              float64
dtype: object

All are correctly formated except 'order_date' column as I can see it data type was in 'object' but it should be in date data type so, I am converting it data type into date.

In [31]:
df['order_date'] = pd.to_datetime(df['order_date'],format = "%Y-%m-%d")

Using pandas function 'to_datetime' and keeping exact format as in the values in dataset so it recongise and changed the entire column datatype

In [33]:
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount_price             float64
sale_price                 float64
profit                     float64
dtype: object

And coming to dataframe , I no longer needed cost_price, list_price and discount_percent columns in my dataframe for my further analysis so I dropping those columns from my dataframe

In [34]:
df.drop(columns=['list_price','cost_price','discount_percent'],inplace = True)

In [35]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount_price,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

In [36]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in /Users/chandupeddi/opt/anaconda3/lib/python3.13/site-packages (2.0.39)
Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in /Users/chandupeddi/opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.12.2)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2
Note: you may need to restart the kernel to use updated packages.

In [40]:
import sqlalchemy as sql
engine = sql.create_engine('mysql+pymysql://root:YOUR_PASSWORD@localhost:3306/orders')
connect = engine.connect()

In [43]:
df.to_sql(name='df_orders', con=connect, if_exists='append', index=False)

9994